# Generated by Django 5.0.6 on 2024-05-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
    ]
