# Generated by Django 5.0.6 on 2024-05-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
